In [2]:
from torch import distributions, tensor

In [3]:
dist = distributions.binomial.Binomial(probs=.75)

In [4]:
t = torch.ones((3,3,3))
t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
m = tensor([1, 0, 1])
m

tensor([1, 0, 1])

In [6]:
m.shape,t.shape

(torch.Size([3]), torch.Size([3, 3, 3]))

In [19]:
m.unsqueeze(1)

tensor([[1],
        [0],
        [1]])

In [33]:
channels = 3
im = torch.randint(0,10,(channels, 5, 5))
im

tensor([[[2, 8, 4, 5, 4],
         [3, 2, 1, 0, 4],
         [3, 6, 1, 3, 5],
         [2, 3, 4, 1, 8],
         [5, 6, 5, 7, 3]],

        [[0, 6, 0, 4, 1],
         [9, 4, 6, 0, 9],
         [5, 9, 9, 6, 7],
         [3, 7, 4, 3, 7],
         [4, 9, 4, 5, 6]],

        [[2, 6, 6, 7, 1],
         [1, 5, 9, 8, 9],
         [9, 3, 0, 4, 2],
         [1, 8, 0, 6, 4],
         [6, 4, 4, 3, 4]]])

In [34]:
drop = dist.sample((channels, 1, 1))
drop,drop.shape

(tensor([[[0.]],
 
         [[1.]],
 
         [[1.]]]),
 torch.Size([3, 1, 1]))

In [35]:
drop * im

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 6., 0., 4., 1.],
         [9., 4., 6., 0., 9.],
         [5., 9., 9., 6., 7.],
         [3., 7., 4., 3., 7.],
         [4., 9., 4., 5., 6.]],

        [[2., 6., 6., 7., 1.],
         [1., 5., 9., 8., 9.],
         [9., 3., 0., 4., 2.],
         [1., 8., 0., 6., 4.],
         [6., 4., 4., 3., 4.]]])